#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [[ "$#" -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1;
elif [[ "$#" -lt 4 ]]; then
	scp "$1" "$3"@"$2":~/
	exit 0;
else
	scp -i "$4" "$1" "$3"@"$2":~/ -o StrictHostKeyChecking=no
	exit 0;
fi
