#!/usr/bin/env bash
# Bash script that installs and configure nginx 

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

ufw allow 'Nginx HTTP'

sudo service nginx restart

sudo echo "Hello World!" > /var/www/html/index.html 
