#!/usr/bin/env bash
# Bash script that installs and configure nginx 

sudo apt update
sudo apt install -y nginx

sudo service nginx start

ufw allow 'Nginx HTTP'

sudo service nginx restart

sudo echo "Hello world!" > /var/www/html/index.html 
