#!/usr/bin/env bash
# Script that configures nginx

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement="server_name _;\n\trewrite ^\/redirect_me http:\/\/www.google.com permanent;"

sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
