#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2 seconds
# It prints "I am invincible!!!" upon receiving a SIGTERM signal

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
