#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# where only the part of the name after the first dash is displayed

list=$(ls)
for file in $list;
do
	filename=$(basename "$file")
	part=$(echo "$filename" | cut -d "-" -f 2)
	echo "$part"
done
